### ISSUE TITLE
Package review

### ISSUE THREAD

**Issue by clhancock** [AubreyLaPlante/copdr#1]
Hi Aubrey,

I enjoyed going through your package. All the code worked fine and I was able to get the vignette to knit. I've attached a document with some minor code suggestions. I didn't really understand the math, so I mostly focused on the plotting function and how the vignette looks They are broken down into 3 sections:
1) Package - Everything works fine. Consider building the html.
2) Vignette - Comments/suggestions about how to make your vignette look nicer/more clear
3) General code -Ccomments/suggestions about your plotting function

[CodeReviewNotes.docx](https://github.com/AubreyLaPlante/copdr/files/14856331/CodeReviewNotes.docx)

**Comment by clhancock** [comment]
Ignore my comment about the data folder. I understand why it's set up that way now

**Comment by AubreyLaPlante** [comment]
I have revised the code to reflect all suggested edits. Thank you!
